"""urgencia y canceladas no bloquean

Revision ID: 3fb05b6732d6
Revises: 9ce081662eba
Create Date: 2026-10-01 17:18:48.309189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb05b6732d6'
down_revision: Union[str, Sequence[str], None] = '9ce081662eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triaje', sa.Column('urgencia', sa.String(length=30), nullable=False))
    op.drop_constraint("citas_no_traslapan", "citas", type_="exclude")
    op.create_exclude_constraint(
        "citas_no_traslapan",
        "citas",
        ("recurso_id", "="),
        ("periodo", "&&"),
        using="gist",
        where="estado <> 'cancelada'",
    )
    op.create_check_constraint(
        "citas_estado_valido",
        "citas",
        "estado IN ('reservada', 'cancelada', 'atendida', 'no_asistio')",
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triaje', 'urgencia')
    op.drop_constraint("citas_no_traslapan", "citas", type_="exclude")
    op.create_exclude_constraint(
        "citas_no_traslapan",
        "citas",
        ("recurso_id", "="),
        ("periodo", "&&"),
        using="gist",
    )
    op.drop_constraint("citas_estado_valido", "citas", type_="check")
    # ### end Alembic commands ###
